# Site settings
title: CodingLove
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://codinglove.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

permalink: /:title

#  List Nama Penulis
authors:
  muslih:
    name: Muslih
    position: Software Developer Intern
    gravatar: d4acca0bcb24dc67644055d4e44a6b29
    web: http://muslih.me
    github: muslih
    twitter: muslihzarth
    about: |    
      Summer intern at Comoyo. Likes front-end development, new technology
      and cake. Currently active as Head of IT for [ISFiT](http://www.isfit.org).